<center> <img src ="https://i.postimg.cc/1X8H7YYt/BITS-Logo.png" width = "400" alt="BITS Pilani Logo" /> </center>

<font color='green'> <h1> <center> Basics of NumPy Arrays - 2 </center> </h1> </font>


In [1]:
import numpy as np

<b> Array Indexing<b>

Similar to list indexing, arrays can be accessed using the indices.

In [2]:
nparray = np.array([1, 2, 3, 4, 5])

In [3]:
#Access first element, indexing starts from 0 
nparray[0]

1

In [11]:
#Access second element, indexing starts from 0 
nparray[1]

2

In [12]:
#Access last element, negative indices works
nparray[-1]

5

In [13]:
nparray[-2]

4

In multi-dimensional arrays, comma separated tuple of indices can be used to access elements.

In [9]:
x = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]]) 
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Access element at location (0, 0), zeroth row and zeroth column
x[(0,0)]

1

In [11]:
#Access element at location (1, 2), first row and second column
x[1,2]

6

Values can be modified using indices,

In [12]:
#Modify the (0, 0)th entry to 555
x[0, 0] = 555
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

<b> Array Slicing<b>

[] can be used access the sub arrays i.e. array sicing is supported similar to list. To access a slice of array x , use : <br>
x[start:stop:step]

In [13]:
nparray

array([1, 2, 3, 4, 5])

In [14]:
nparray[1:]  # all values after index 1

array([2, 3, 4, 5])

In [15]:
nparray[ : 3] # all values till index 3

array([1, 2, 3])

In [16]:
nparray[2:4] # all value between index 2 and 4

array([3, 4])

In [17]:
nparray[::2]  #every other element

array([1, 3, 5])

In [18]:
nparray[1::2]  #every other element starting from element at index 1

array([2, 4])

In [19]:
nparray[::-1] # all elements in reversed direction

array([5, 4, 3, 2, 1])

In [20]:
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [21]:
x[ : 2, : 3] # first two rows, first three columns

array([[555,   2,   3],
       [  4,   5,   6]])

In [22]:
#Accessing array rows 
x[0, :]  # zeroth row , all columns

array([555,   2,   3])

In [23]:
#Accessing array columns
x[:, 1]  # all row , second columns

array([2, 5, 8])

<b> Array copying<b>

Array slices are views, hence if they are modified then original array is changed.

In [24]:
nparray

array([1, 2, 3, 4, 5])

In [25]:
nparray_sub = nparray[2:4]   #Slice the array 
nparray_sub

array([3, 4])

In [26]:
nparray_sub[0] = 5  # modify the element of slice
nparray_sub

array([5, 4])

In [27]:
nparray #original array is changed

array([1, 2, 5, 4, 5])

In order to prevent this behaviour copy needs to be done.

In [28]:
nparray_copy = nparray[2:4].copy()  #create copy of array slice

In [29]:
nparray_copy[0] = 90  # modify the slice 
nparray_copy

array([90,  4])

In [30]:
nparray  #original array is still intact

array([1, 2, 5, 4, 5])

<b> Reshaping of Arrays <b>

Reshape can be used to change the structure of array. Size of original and reshaped arrays should be same.

In [31]:
a = [ 1, 2, 3, 4, 5, 6, 7, 8, 9]
array = np.array(a)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
array.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Reshaping can be used to convert an array into row matrix or column matrix.

In [33]:
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [34]:
x.reshape(9, 1)

array([[555],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [35]:
x.reshape(1, 9)

array([[555,   2,   3,   4,   5,   6,   7,   8,   9]])

<b> Array Concatenation<b>

Joining of two arrays is possible through np.concatenate, np.vstack and np.hstack.

In [36]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = np.array([99, 99, 99])

In [37]:
np.concatenate([x, y, z])

array([ 1,  2,  3, 10, 20, 30, 99, 99, 99])

In [38]:
two_d_array = np.array([[1, 2, 3], [4, 5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([two_d_array, two_d_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
# used to vertically stack arrays. It stacks arrays one on top of the other along the vertical axis (row-wise).
#When you provide two arrays to np.vstack(), they should have the same number of columns, but they can have different numbers of rows.
np.vstack([two_d_array, y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [42]:
v_array = np.array([[99], [99]])
v_array

array([[99],
       [99]])

In [43]:
#used to horizontally stack arrays. It concatenates arrays side by side along the horizontal axis (column-wise). 
#When you provide two arrays to np.hstack(), they should have the same number of rows, but they can have different numbers of columns.
np.hstack([two_d_array, v_array])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

<b> Array Splitting<b>

Splititng is done by split, vsplit and hsplit.

In [44]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [45]:
n1, n2, n3, n4 = np.split(x, [2, 5, 8 ])   # splitting position 2, 5, and 8 

In [46]:
print(n1, n2, n3, n4)

[1 2] [3 4 5] [6 7 8] [ 9 10]


<b> Fancy Indexing<b>

Here arrays of indices is passed to access the elements.

In [47]:
nparray

array([1, 2, 5, 4, 5])

In [48]:
indices = [1, 3, 4]  #indices first, third and fourth
nparray[indices] #elements at first , third and forth elements are returned

array([2, 4, 5])